### ISSUE TITLE
Linking the Apple Pie Image

### ISSUE THREAD

**Issue by dan11011** [Media-Ed-Online/intro-web-dev-resources-summer#5]
Hello, for some reason when I open my site online the apple pie image at the top of the recipe is not there. However, I've checked my code quite a few times and it always shows up in both the preview mode and when I click on the html link on my computer. It just doesn't show when I use the https link. The first image shows atom with the photo displaying, the second photo shows the site without the image displaying and the third photo shows the file opened from my computer with the image displaying. Any thoughts?
<img width="929" alt="screen shot 2018-06-04 at 8 49 13 pm" src="https://user-images.githubusercontent.com/39507641/40935597-e4bbcf14-6838-11e8-9740-9711d8856543.png">
<img width="715" alt="screen shot 2018-06-04 at 8 58 28 pm" src="https://user-images.githubusercontent.com/39507641/40935754-5a623140-6839-11e8-9d28-cc96760e1760.png">
<img width="804" alt="screen shot 2018-06-04 at 9 00 36 pm" src="https://user-images.githubusercontent.com/39507641/40935811-88263054-6839-11e8-8ed3-f06ebbec3501.png">

**Comment by DVSnell** [comment]
You've got ```<img src="/Users/danielostersmith/Documents/GitHub/web-dev-hw/assignment-3/images/apple-pie.jpg">```
for your actual Github code which returns   <img src="/Users/danielostersmith/Documents/GitHub/web-dev-hw/assignment-3/images/apple-pie.jpg">
so maybe try pushing another update.

**Comment by dan11011** [comment]
That was it! Thank you so much!
